version: "3.9"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb://mongo_db:27017/MovieAppDB
      - APPLICATION_PORT=3000
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_db:/data/db
volumes:
  mongo_db: {}
